### ISSUE TITLE
MRF course quiz query

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/eLearning-modules#1]
I had a look at the MRF course today and noticed on the end quiz that it talks about preferred order for the waste hierachy rather than the prioritised order. Is this correct? Preferred sounds like its up for discussion rather than set in the directive?
![mrf screenshot](https://cloud.githubusercontent.com/assets/13269824/9110567/a2a34638-3c36-11e5-8a1b-3fc3daed23a8.jpg)

**Comment by nick69g** [comment]
That's a good point. Happy to change it.

**Comment by nick69g** [comment]
This has now been updated with "priority".
